namespace BookLibrary.Forms.Books
{
    partial class frmEditBook
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmEditBook));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.lbSetImage = new System.Windows.Forms.LinkLabel();
            this.label12 = new System.Windows.Forms.Label();
            this.btnCancle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dpPublishDate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.pbBookImage = new System.Windows.Forms.PictureBox();
            this.tbQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbAdditionalDetails = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbGenre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbAuther = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbISBN = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbMode = new System.Windows.Forms.Label();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbBookImage)).BeginInit();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tbQuantity);
            this.groupBox1.Controls.Add(this.tbAdditionalDetails);
            this.groupBox1.Controls.Add(this.tbGenre);
            this.groupBox1.Controls.Add(this.tbAuther);
            this.groupBox1.Controls.Add(this.tbISBN);
            this.groupBox1.Controls.Add(this.tbTitle);
            this.groupBox1.Controls.Add(this.btnCancle);
            this.groupBox1.Controls.Add(this.btnSave);
            this.groupBox1.Controls.Add(this.dpPublishDate);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.lbSetImage);
            this.groupBox1.Controls.Add(this.pbBookImage);
            this.groupBox1.Location = new System.Drawing.Point(14, 38);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(620, 379);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Enter += new System.EventHandler(this.groupBox1_Enter);
            // 
            // lbSetImage
            // 
            this.lbSetImage.AutoSize = true;
            this.lbSetImage.Font = new System.Drawing.Font("Constantia", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbSetImage.Location = new System.Drawing.Point(396, 163);
            this.lbSetImage.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbSetImage.Name = "lbSetImage";
            this.lbSetImage.Size = new System.Drawing.Size(72, 18);
            this.lbSetImage.TabIndex = 30;
            this.lbSetImage.TabStop = true;
            this.lbSetImage.Text = "Set Image";
            this.lbSetImage.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbSetImage_LinkClicked);
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Constantia", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(325, 202);
            this.label12.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(101, 18);
            this.label12.TabIndex = 31;
            this.label12.Text = "Publish Date";
            // 
            // btnCancle
            // 
            this.btnCancle.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.btnCancle.AllowAnimations = true;
            this.btnCancle.AllowMouseEffects = true;
            this.btnCancle.AllowToggling = false;
            this.btnCancle.AnimationSpeed = 200;
            this.btnCancle.AutoGenerateColors = false;
            this.btnCancle.AutoRoundBorders = false;
            this.btnCancle.AutoSizeLeftIcon = true;
            this.btnCancle.AutoSizeRightIcon = true;
            this.btnCancle.BackColor = System.Drawing.Color.Transparent;
            this.btnCancle.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCancle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancle.BackgroundImage")));
            this.btnCancle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancle.ButtonText = "Cancle";
            this.btnCancle.ButtonTextMarginLeft = 0;
            this.btnCancle.ColorContrastOnClick = 45;
            this.btnCancle.ColorContrastOnHover = 45;
            this.btnCancle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnCancle.CustomizableEdges = borderEdges1;
            this.btnCancle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCancle.ForeColor = System.Drawing.Color.White;
            this.btnCancle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancle.IconMarginLeft = 11;
            this.btnCancle.IconPadding = 10;
            this.btnCancle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancle.IconSize = 25;
            this.btnCancle.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCancle.IdleBorderRadius = 25;
            this.btnCancle.IdleBorderThickness = 1;
            this.btnCancle.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCancle.IdleIconLeftImage = null;
            this.btnCancle.IdleIconRightImage = null;
            this.btnCancle.IndicateFocus = false;
            this.btnCancle.Location = new System.Drawing.Point(319, 328);
            this.btnCancle.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancle.Name = "btnCancle";
            this.btnCancle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancle.OnDisabledState.BorderRadius = 25;
            this.btnCancle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancle.OnDisabledState.BorderThickness = 1;
            this.btnCancle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancle.OnDisabledState.IconLeftImage = null;
            this.btnCancle.OnDisabledState.IconRightImage = null;
            this.btnCancle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancle.onHoverState.BorderRadius = 25;
            this.btnCancle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancle.onHoverState.BorderThickness = 1;
            this.btnCancle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancle.onHoverState.IconLeftImage = null;
            this.btnCancle.onHoverState.IconRightImage = null;
            this.btnCancle.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCancle.OnIdleState.BorderRadius = 25;
            this.btnCancle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancle.OnIdleState.BorderThickness = 1;
            this.btnCancle.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCancle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancle.OnIdleState.IconLeftImage = null;
            this.btnCancle.OnIdleState.IconRightImage = null;
            this.btnCancle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancle.OnPressedState.BorderRadius = 25;
            this.btnCancle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancle.OnPressedState.BorderThickness = 1;
            this.btnCancle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancle.OnPressedState.IconLeftImage = null;
            this.btnCancle.OnPressedState.IconRightImage = null;
            this.btnCancle.Size = new System.Drawing.Size(115, 37);
            this.btnCancle.TabIndex = 39;
            this.btnCancle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancle.TextMarginLeft = 0;
            this.btnCancle.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancle.UseDefaultRadiusAndThickness = true;
            this.btnCancle.Click += new System.EventHandler(this.btnCancle_Click);
            // 
            // btnSave
            // 
            this.btnSave.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges2;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleBorderRadius = 25;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(454, 328);
            this.btnSave.Margin = new System.Windows.Forms.Padding(4);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 25;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 25;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 25;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 25;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(115, 37);
            this.btnSave.TabIndex = 38;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // dpPublishDate
            // 
            this.dpPublishDate.BackColor = System.Drawing.Color.Transparent;
            this.dpPublishDate.BorderRadius = 11;
            this.dpPublishDate.Color = System.Drawing.Color.Silver;
            this.dpPublishDate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dpPublishDate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dpPublishDate.DisabledColor = System.Drawing.Color.Gray;
            this.dpPublishDate.DisplayWeekNumbers = false;
            this.dpPublishDate.DPHeight = 0;
            this.dpPublishDate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dpPublishDate.FillDatePicker = false;
            this.dpPublishDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dpPublishDate.ForeColor = System.Drawing.Color.Black;
            this.dpPublishDate.Icon = ((System.Drawing.Image)(resources.GetObject("dpPublishDate.Icon")));
            this.dpPublishDate.IconColor = System.Drawing.Color.Gray;
            this.dpPublishDate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dpPublishDate.LeftTextMargin = 5;
            this.dpPublishDate.Location = new System.Drawing.Point(319, 226);
            this.dpPublishDate.MinimumSize = new System.Drawing.Size(4, 32);
            this.dpPublishDate.Name = "dpPublishDate";
            this.dpPublishDate.Size = new System.Drawing.Size(250, 32);
            this.dpPublishDate.TabIndex = 32;
            // 
            // pbBookImage
            // 
            this.pbBookImage.Image = global::BookLibrary.Properties.Resources.books;
            this.pbBookImage.Location = new System.Drawing.Point(372, 36);
            this.pbBookImage.Name = "pbBookImage";
            this.pbBookImage.Size = new System.Drawing.Size(116, 116);
            this.pbBookImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbBookImage.TabIndex = 8;
            this.pbBookImage.TabStop = false;
            // 
            // tbQuantity
            // 
            this.tbQuantity.AcceptsReturn = false;
            this.tbQuantity.AcceptsTab = false;
            this.tbQuantity.AnimationSpeed = 200;
            this.tbQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbQuantity.BackColor = System.Drawing.Color.Transparent;
            this.tbQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbQuantity.BackgroundImage")));
            this.tbQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbQuantity.BorderRadius = 25;
            this.tbQuantity.BorderThickness = 1;
            this.tbQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbQuantity.DefaultText = "";
            this.tbQuantity.FillColor = System.Drawing.Color.White;
            this.tbQuantity.HideSelection = true;
            this.tbQuantity.IconLeft = null;
            this.tbQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantity.IconPadding = 10;
            this.tbQuantity.IconRight = null;
            this.tbQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantity.Lines = new string[0];
            this.tbQuantity.Location = new System.Drawing.Point(28, 319);
            this.tbQuantity.Margin = new System.Windows.Forms.Padding(4);
            this.tbQuantity.MaxLength = 32767;
            this.tbQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbQuantity.Modified = false;
            this.tbQuantity.Multiline = false;
            this.tbQuantity.Name = "tbQuantity";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantity.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbQuantity.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantity.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantity.OnIdleState = stateProperties4;
            this.tbQuantity.Padding = new System.Windows.Forms.Padding(4);
            this.tbQuantity.PasswordChar = '\0';
            this.tbQuantity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbQuantity.PlaceholderText = "Quantity";
            this.tbQuantity.ReadOnly = false;
            this.tbQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbQuantity.SelectedText = "";
            this.tbQuantity.SelectionLength = 0;
            this.tbQuantity.SelectionStart = 0;
            this.tbQuantity.ShortcutsEnabled = true;
            this.tbQuantity.Size = new System.Drawing.Size(241, 40);
            this.tbQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbQuantity.TabIndex = 54;
            this.tbQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbQuantity.TextMarginBottom = 0;
            this.tbQuantity.TextMarginLeft = 3;
            this.tbQuantity.TextMarginTop = 0;
            this.tbQuantity.TextPlaceholder = "Quantity";
            this.tbQuantity.UseSystemPasswordChar = false;
            this.tbQuantity.WordWrap = true;
            // 
            // tbAdditionalDetails
            // 
            this.tbAdditionalDetails.AcceptsReturn = false;
            this.tbAdditionalDetails.AcceptsTab = false;
            this.tbAdditionalDetails.AnimationSpeed = 200;
            this.tbAdditionalDetails.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAdditionalDetails.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAdditionalDetails.BackColor = System.Drawing.Color.Transparent;
            this.tbAdditionalDetails.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAdditionalDetails.BackgroundImage")));
            this.tbAdditionalDetails.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAdditionalDetails.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAdditionalDetails.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAdditionalDetails.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAdditionalDetails.BorderRadius = 25;
            this.tbAdditionalDetails.BorderThickness = 1;
            this.tbAdditionalDetails.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAdditionalDetails.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAdditionalDetails.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbAdditionalDetails.DefaultText = "";
            this.tbAdditionalDetails.FillColor = System.Drawing.Color.White;
            this.tbAdditionalDetails.HideSelection = true;
            this.tbAdditionalDetails.IconLeft = null;
            this.tbAdditionalDetails.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAdditionalDetails.IconPadding = 10;
            this.tbAdditionalDetails.IconRight = null;
            this.tbAdditionalDetails.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAdditionalDetails.Lines = new string[0];
            this.tbAdditionalDetails.Location = new System.Drawing.Point(28, 262);
            this.tbAdditionalDetails.Margin = new System.Windows.Forms.Padding(4);
            this.tbAdditionalDetails.MaxLength = 32767;
            this.tbAdditionalDetails.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAdditionalDetails.Modified = false;
            this.tbAdditionalDetails.Multiline = false;
            this.tbAdditionalDetails.Name = "tbAdditionalDetails";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAdditionalDetails.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAdditionalDetails.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAdditionalDetails.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAdditionalDetails.OnIdleState = stateProperties8;
            this.tbAdditionalDetails.Padding = new System.Windows.Forms.Padding(4);
            this.tbAdditionalDetails.PasswordChar = '\0';
            this.tbAdditionalDetails.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAdditionalDetails.PlaceholderText = "AdditionalDetails";
            this.tbAdditionalDetails.ReadOnly = false;
            this.tbAdditionalDetails.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAdditionalDetails.SelectedText = "";
            this.tbAdditionalDetails.SelectionLength = 0;
            this.tbAdditionalDetails.SelectionStart = 0;
            this.tbAdditionalDetails.ShortcutsEnabled = true;
            this.tbAdditionalDetails.Size = new System.Drawing.Size(241, 40);
            this.tbAdditionalDetails.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAdditionalDetails.TabIndex = 53;
            this.tbAdditionalDetails.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAdditionalDetails.TextMarginBottom = 0;
            this.tbAdditionalDetails.TextMarginLeft = 3;
            this.tbAdditionalDetails.TextMarginTop = 0;
            this.tbAdditionalDetails.TextPlaceholder = "AdditionalDetails";
            this.tbAdditionalDetails.UseSystemPasswordChar = false;
            this.tbAdditionalDetails.WordWrap = true;
            // 
            // tbGenre
            // 
            this.tbGenre.AcceptsReturn = false;
            this.tbGenre.AcceptsTab = false;
            this.tbGenre.AnimationSpeed = 200;
            this.tbGenre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbGenre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbGenre.BackColor = System.Drawing.Color.Transparent;
            this.tbGenre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbGenre.BackgroundImage")));
            this.tbGenre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbGenre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbGenre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbGenre.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbGenre.BorderRadius = 25;
            this.tbGenre.BorderThickness = 1;
            this.tbGenre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbGenre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbGenre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbGenre.DefaultText = "";
            this.tbGenre.FillColor = System.Drawing.Color.White;
            this.tbGenre.HideSelection = true;
            this.tbGenre.IconLeft = null;
            this.tbGenre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbGenre.IconPadding = 10;
            this.tbGenre.IconRight = null;
            this.tbGenre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbGenre.Lines = new string[0];
            this.tbGenre.Location = new System.Drawing.Point(28, 205);
            this.tbGenre.Margin = new System.Windows.Forms.Padding(4);
            this.tbGenre.MaxLength = 32767;
            this.tbGenre.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbGenre.Modified = false;
            this.tbGenre.Multiline = false;
            this.tbGenre.Name = "tbGenre";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbGenre.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbGenre.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbGenre.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbGenre.OnIdleState = stateProperties12;
            this.tbGenre.Padding = new System.Windows.Forms.Padding(4);
            this.tbGenre.PasswordChar = '\0';
            this.tbGenre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbGenre.PlaceholderText = "Genre";
            this.tbGenre.ReadOnly = false;
            this.tbGenre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbGenre.SelectedText = "";
            this.tbGenre.SelectionLength = 0;
            this.tbGenre.SelectionStart = 0;
            this.tbGenre.ShortcutsEnabled = true;
            this.tbGenre.Size = new System.Drawing.Size(241, 40);
            this.tbGenre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbGenre.TabIndex = 52;
            this.tbGenre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbGenre.TextMarginBottom = 0;
            this.tbGenre.TextMarginLeft = 3;
            this.tbGenre.TextMarginTop = 0;
            this.tbGenre.TextPlaceholder = "Genre";
            this.tbGenre.UseSystemPasswordChar = false;
            this.tbGenre.WordWrap = true;
            // 
            // tbAuther
            // 
            this.tbAuther.AcceptsReturn = false;
            this.tbAuther.AcceptsTab = false;
            this.tbAuther.AnimationSpeed = 200;
            this.tbAuther.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAuther.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAuther.BackColor = System.Drawing.Color.Transparent;
            this.tbAuther.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAuther.BackgroundImage")));
            this.tbAuther.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAuther.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAuther.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAuther.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAuther.BorderRadius = 25;
            this.tbAuther.BorderThickness = 1;
            this.tbAuther.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAuther.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAuther.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbAuther.DefaultText = "";
            this.tbAuther.FillColor = System.Drawing.Color.White;
            this.tbAuther.HideSelection = true;
            this.tbAuther.IconLeft = null;
            this.tbAuther.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAuther.IconPadding = 10;
            this.tbAuther.IconRight = null;
            this.tbAuther.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAuther.Lines = new string[0];
            this.tbAuther.Location = new System.Drawing.Point(28, 92);
            this.tbAuther.Margin = new System.Windows.Forms.Padding(4);
            this.tbAuther.MaxLength = 32767;
            this.tbAuther.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAuther.Modified = false;
            this.tbAuther.Multiline = false;
            this.tbAuther.Name = "tbAuther";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAuther.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAuther.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAuther.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAuther.OnIdleState = stateProperties16;
            this.tbAuther.Padding = new System.Windows.Forms.Padding(4);
            this.tbAuther.PasswordChar = '\0';
            this.tbAuther.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAuther.PlaceholderText = "Auther";
            this.tbAuther.ReadOnly = false;
            this.tbAuther.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAuther.SelectedText = "";
            this.tbAuther.SelectionLength = 0;
            this.tbAuther.SelectionStart = 0;
            this.tbAuther.ShortcutsEnabled = true;
            this.tbAuther.Size = new System.Drawing.Size(241, 40);
            this.tbAuther.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAuther.TabIndex = 51;
            this.tbAuther.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAuther.TextMarginBottom = 0;
            this.tbAuther.TextMarginLeft = 3;
            this.tbAuther.TextMarginTop = 0;
            this.tbAuther.TextPlaceholder = "Auther";
            this.tbAuther.UseSystemPasswordChar = false;
            this.tbAuther.WordWrap = true;
            // 
            // tbISBN
            // 
            this.tbISBN.AcceptsReturn = false;
            this.tbISBN.AcceptsTab = false;
            this.tbISBN.AnimationSpeed = 200;
            this.tbISBN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbISBN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbISBN.BackColor = System.Drawing.Color.Transparent;
            this.tbISBN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbISBN.BackgroundImage")));
            this.tbISBN.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbISBN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbISBN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbISBN.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbISBN.BorderRadius = 25;
            this.tbISBN.BorderThickness = 1;
            this.tbISBN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbISBN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbISBN.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbISBN.DefaultText = "";
            this.tbISBN.FillColor = System.Drawing.Color.White;
            this.tbISBN.HideSelection = true;
            this.tbISBN.IconLeft = null;
            this.tbISBN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbISBN.IconPadding = 10;
            this.tbISBN.IconRight = null;
            this.tbISBN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbISBN.Lines = new string[0];
            this.tbISBN.Location = new System.Drawing.Point(28, 149);
            this.tbISBN.Margin = new System.Windows.Forms.Padding(4);
            this.tbISBN.MaxLength = 32767;
            this.tbISBN.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbISBN.Modified = false;
            this.tbISBN.Multiline = false;
            this.tbISBN.Name = "tbISBN";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbISBN.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbISBN.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbISBN.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbISBN.OnIdleState = stateProperties20;
            this.tbISBN.Padding = new System.Windows.Forms.Padding(4);
            this.tbISBN.PasswordChar = '\0';
            this.tbISBN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbISBN.PlaceholderText = "ISBN Code";
            this.tbISBN.ReadOnly = false;
            this.tbISBN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbISBN.SelectedText = "";
            this.tbISBN.SelectionLength = 0;
            this.tbISBN.SelectionStart = 0;
            this.tbISBN.ShortcutsEnabled = true;
            this.tbISBN.Size = new System.Drawing.Size(241, 40);
            this.tbISBN.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbISBN.TabIndex = 50;
            this.tbISBN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbISBN.TextMarginBottom = 0;
            this.tbISBN.TextMarginLeft = 3;
            this.tbISBN.TextMarginTop = 0;
            this.tbISBN.TextPlaceholder = "ISBN Code";
            this.tbISBN.UseSystemPasswordChar = false;
            this.tbISBN.WordWrap = true;
            // 
            // tbTitle
            // 
            this.tbTitle.AcceptsReturn = false;
            this.tbTitle.AcceptsTab = false;
            this.tbTitle.AnimationSpeed = 200;
            this.tbTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbTitle.BackColor = System.Drawing.Color.Transparent;
            this.tbTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbTitle.BackgroundImage")));
            this.tbTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbTitle.BorderRadius = 25;
            this.tbTitle.BorderThickness = 1;
            this.tbTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbTitle.DefaultText = "";
            this.tbTitle.FillColor = System.Drawing.Color.White;
            this.tbTitle.HideSelection = true;
            this.tbTitle.IconLeft = null;
            this.tbTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTitle.IconPadding = 10;
            this.tbTitle.IconRight = null;
            this.tbTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTitle.Lines = new string[0];
            this.tbTitle.Location = new System.Drawing.Point(28, 36);
            this.tbTitle.Margin = new System.Windows.Forms.Padding(4);
            this.tbTitle.MaxLength = 32767;
            this.tbTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbTitle.Modified = false;
            this.tbTitle.Multiline = false;
            this.tbTitle.Name = "tbTitle";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTitle.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbTitle.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTitle.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTitle.OnIdleState = stateProperties24;
            this.tbTitle.Padding = new System.Windows.Forms.Padding(4);
            this.tbTitle.PasswordChar = '\0';
            this.tbTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbTitle.PlaceholderText = "Title";
            this.tbTitle.ReadOnly = false;
            this.tbTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbTitle.SelectedText = "";
            this.tbTitle.SelectionLength = 0;
            this.tbTitle.SelectionStart = 0;
            this.tbTitle.ShortcutsEnabled = true;
            this.tbTitle.Size = new System.Drawing.Size(241, 40);
            this.tbTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbTitle.TabIndex = 49;
            this.tbTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbTitle.TextMarginBottom = 0;
            this.tbTitle.TextMarginLeft = 3;
            this.tbTitle.TextMarginTop = 0;
            this.tbTitle.TextPlaceholder = "Title";
            this.tbTitle.UseSystemPasswordChar = false;
            this.tbTitle.WordWrap = true;
            // 
            // lbMode
            // 
            this.lbMode.AutoSize = true;
            this.lbMode.Font = new System.Drawing.Font("Constantia", 13.75F, System.Drawing.FontStyle.Bold);
            this.lbMode.ForeColor = System.Drawing.Color.IndianRed;
            this.lbMode.Location = new System.Drawing.Point(270, 9);
            this.lbMode.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbMode.Name = "lbMode";
            this.lbMode.Size = new System.Drawing.Size(98, 23);
            this.lbMode.TabIndex = 11;
            this.lbMode.Text = "Edit Book";
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // frmEditBook
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(657, 435);
            this.Controls.Add(this.lbMode);
            this.Controls.Add(this.groupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmEditBook";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmEditBook";
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbBookImage)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.PictureBox pbBookImage;
        private System.Windows.Forms.LinkLabel lbSetImage;
        private Bunifu.UI.WinForms.BunifuDatePicker dpPublishDate;
        private System.Windows.Forms.Label label12;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuTextBox tbQuantity;
        private Bunifu.UI.WinForms.BunifuTextBox tbAdditionalDetails;
        private Bunifu.UI.WinForms.BunifuTextBox tbGenre;
        private Bunifu.UI.WinForms.BunifuTextBox tbAuther;
        private Bunifu.UI.WinForms.BunifuTextBox tbISBN;
        private Bunifu.UI.WinForms.BunifuTextBox tbTitle;
        private System.Windows.Forms.Label lbMode;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
    }
}